CREATE TABLE `glvar_property_listing` (
  `Accessibility_Features` text,
  `Active_Open_House_Count` int(11) DEFAULT NULL,
  `Additional_AU_Sold_Terms` varchar(100) DEFAULT NULL,
  `Additional_Liv_Area` text,
  `Additional_Pet_Rent_YN` tinyint(1) DEFAULT NULL,
  `Administration_Deposit` int(11) DEFAULT NULL,
  `Administration_Fee_YN` tinyint(1) DEFAULT NULL,
  `Administration_Refund` varchar(100) DEFAULT NULL,
  `Age_Restricted_Community_YN` tinyint(1) DEFAULT NULL,
  `Amt_Owner_Will_Carry` int(11) DEFAULT NULL,
  `Annual_Property_Taxes` int(11) DEFAULT NULL,
  `Application_Fee_Amount` decimal(14,2) DEFAULT NULL,
  `Application_Fee_YN` tinyint(1) DEFAULT NULL,
  `Approx_Addl_Liv_Area` int(11) DEFAULT NULL,
  `Approx_Total_Liv_Area` int(11) DEFAULT NULL,
  `Appx_Association_Fee` int(11) DEFAULT NULL,
  `Appx_Subfee_Amount` int(11) DEFAULT NULL,
  `Appx_Subfee_Pymt_Ty` varchar(100) DEFAULT NULL,
  `Area` varchar(100) DEFAULT NULL,
  `Assessed_Imp_Value` int(11) DEFAULT NULL,
  `Assessed_Land_Value` int(11) DEFAULT NULL,
  `Assessment_Balance` int(11) DEFAULT NULL,
  `Assessments` int(11) DEFAULT NULL,
  `Assessment_Type` varchar(100) DEFAULT NULL,
  `Assessment_YN` tinyint(1) DEFAULT NULL,
  `Association_Features_Available` text,
  `Association_Fee_1` int(11) DEFAULT NULL,
  `Association_Fee_1_MQYN` varchar(100) DEFAULT NULL,
  `Association_Fee_2` int(11) DEFAULT NULL,
  `Association_Fee_2_MQYN` varchar(100) DEFAULT NULL,
  `Association_Fee_Includes` text,
  `Association_Fee_MQYN` varchar(100) DEFAULT NULL,
  `Association_Fee_YN` tinyint(1) DEFAULT NULL,
  `Association_Name` varchar(45) DEFAULT NULL,
  `Association_Phone` varchar(37) DEFAULT NULL,
  `Auction_Date` datetime DEFAULT NULL,
  `Auction_Type` varchar(100) DEFAULT NULL,
  `AVMYN` tinyint(1) DEFAULT NULL,
  `Bath_Downstairs_Description` varchar(100) DEFAULT NULL,
  `Bath_Down_YN` tinyint(1) DEFAULT NULL,
  `Baths_Full` int(11) DEFAULT NULL,
  `Baths_Half` int(11) DEFAULT NULL,
  `Baths_Total` decimal(14,2) DEFAULT NULL,
  `Bedand_Bath_Down_YN` tinyint(1) DEFAULT NULL,
  `Bedroom_Downstairs_YN` tinyint(1) DEFAULT NULL,
  `Bedrooms_Total_Possible_Num` int(11) DEFAULT NULL,
  `Beds_Total` int(11) DEFAULT NULL,
  `Block_Number` varchar(30) DEFAULT NULL,
  `Bonus_SOYN` tinyint(1) DEFAULT NULL,
  `Branded_Virtual_Tour` varchar(280) DEFAULT NULL,
  `Builder` varchar(35) DEFAULT NULL,
  `Building_Description` text,
  `Building_Number` varchar(28) DEFAULT NULL,
  `Built_Description` varchar(100) DEFAULT NULL,
  `Buyer_Premium` decimal(14,2) DEFAULT NULL,
  `Cable_Available` tinyint(1) DEFAULT NULL,
  `Cap_Rate` decimal(14,2) DEFAULT NULL,
  `Carport_Description` varchar(100) DEFAULT NULL,
  `Carports` int(11) DEFAULT NULL,
  `Cashto_Assume` int(11) DEFAULT NULL,
  `Census_Tract` varchar(35) DEFAULT NULL,
  `City` varchar(57) DEFAULT NULL,
  `Cleaning_Deposit` int(11) DEFAULT NULL,
  `Cleaning_Refund` varchar(100) DEFAULT NULL,
  `Close_Date` date DEFAULT NULL,
  `Close_Price` decimal(14,2) DEFAULT NULL,
  `Community_Name` varchar(100) DEFAULT NULL,
  `Compactor_YN` tinyint(1) DEFAULT NULL,
  `Conditional_Date` date DEFAULT NULL,
  `Condo_Conversion_YN` tinyint(1) DEFAULT NULL,
  `Construction_Description` text,
  `Construction_Estimate_End` date DEFAULT NULL,
  `Construction_Estimate_Start` date DEFAULT NULL,
  `Contingency_Desc` varchar(100) DEFAULT NULL,
  `Converted_Garage_YN` tinyint(1) DEFAULT NULL,
  `Convertedto_Real_Property` tinyint(1) DEFAULT NULL,
  `Cooling_Description` text,
  `Cooling_Fuel` varchar(100) DEFAULT NULL,
  `Costper_Unit` int(11) DEFAULT NULL,
  `County_Or_Parish` varchar(57) DEFAULT NULL,
  `Court_Approval` tinyint(1) DEFAULT NULL,
  `Cross_Street` varchar(45) DEFAULT NULL,
  `Current_Loan_Assumable` tinyint(1) DEFAULT NULL,
  `Current_Price` decimal(14,2) DEFAULT NULL,
  `Date_Available` datetime DEFAULT NULL,
  `Deposit` text,
  `Directions` varchar(525) DEFAULT NULL,
  `Dishwasher_Description` text,
  `Dishwasher_YN` tinyint(1) DEFAULT NULL,
  `Disposal_YN` tinyint(1) DEFAULT NULL,
  `DOM` int(11) DEFAULT NULL,
  `Dom_Modifier_Date_Time` datetime DEFAULT NULL,
  `Dom_Modifier_Initial` int(11) DEFAULT NULL,
  `Dom_Modifier_Status_R_Value` varchar(50) DEFAULT NULL,
  `Down_Payment` int(11) DEFAULT NULL,
  `Dryer_Included` tinyint(1) DEFAULT NULL,
  `Dryer_Utilities` varchar(100) DEFAULT NULL,
  `Earnest_Deposit` int(11) DEFAULT NULL,
  `Electricity` text,
  `Elementary_School_35` varchar(100) DEFAULT NULL,
  `Elementary_School_K_2` varchar(100) DEFAULT NULL,
  `Elevator_Floor_Num` int(11) DEFAULT NULL,
  `Energy_Description` text,
  `Environment_Survey` tinyint(1) DEFAULT NULL,
  `Equestrian_Description` text,
  `Est_Clo_Lsedt` datetime DEFAULT NULL,
  `Existing_Rent` int(11) DEFAULT NULL,
  `Expense_Source` text,
  `Exterior_Description` text,
  `Fence` varchar(100) DEFAULT NULL,
  `Fence_Type` text,
  `Financing_Considered` text,
  `Fireplace` tinyint(1) DEFAULT NULL,
  `Fireplace_Description` text,
  `Fireplace_Location` text,
  `Fireplaces` int(11) DEFAULT NULL,
  `First_Encumbrance_Assumable` varchar(100) DEFAULT NULL,
  `First_Encumbrance_Balance` int(11) DEFAULT NULL,
  `First_Encumbrance_Payment` int(11) DEFAULT NULL,
  `First_Encumbrance_Pmt_Desc` text,
  `First_Encumbrance_Rate` decimal(14,2) DEFAULT NULL,
  `Flood_Zone` varchar(100) DEFAULT NULL,
  `Flooring_Description` text,
  `Foreclosure_Commenced_YN` tinyint(1) DEFAULT NULL,
  `Furnished_YN` tinyint(1) DEFAULT NULL,
  `Furnishings_Description` text,
  `Furniture_Included` text,
  `Garage` int(11) DEFAULT NULL,
  `Garage_Description` text,
  `Gas_Description` text,
  `Gated_YN` tinyint(1) DEFAULT NULL,
  `Gravel_Road` varchar(100) DEFAULT NULL,
  `Green_Building_Certification_YN` tinyint(1) DEFAULT NULL,
  `Green_Certification_Rating` varchar(100) DEFAULT NULL,
  `Green_Certifying_Body` varchar(100) DEFAULT NULL,
  `Green_Features` text,
  `Green_Year_Certified` int(11) DEFAULT NULL,
  `Gross_Operating_Income` int(11) DEFAULT NULL,
  `Gross_Rent_Multiplier` decimal(14,2) DEFAULT NULL,
  `Ground_Mounted_YN` tinyint(1) DEFAULT NULL,
  `Handicap_Adapted` tinyint(1) DEFAULT NULL,
  `Heating_Description` text,
  `Heating_Fuel` text,
  `Hidden_Franchise_IDX_Opt_In_YN` tinyint(1) DEFAULT NULL,
  `Highlights` varchar(45) DEFAULT NULL,
  `High_School` varchar(100) DEFAULT NULL,
  `HOA_Minimum_Rental_Cycle` varchar(100) DEFAULT NULL,
  `HOAYN` tinyint(1) DEFAULT NULL,
  `Homeowner_Association_Name` varchar(45) DEFAULT NULL,
  `Homeowner_Association_Phone_No` varchar(37) DEFAULT NULL,
  `Home_Protection_Plan` tinyint(1) DEFAULT NULL,
  `Hot_Water` varchar(100) DEFAULT NULL,
  `House_Faces` text,
  `House_Views` text,
  `IDX` varchar(26) DEFAULT NULL,
  `IDX_Opt_In_YN` tinyint(1) DEFAULT NULL,
  `Interior` text,
  `Internet_YN` tinyint(1) DEFAULT NULL,
  `Jr_High_School` varchar(100) DEFAULT NULL,
  `Junior_Suiteunder_600_Sqft` tinyint(1) DEFAULT NULL,
  `Key_Deposit` int(11) DEFAULT NULL,
  `Key_Refund` varchar(100) DEFAULT NULL,
  `Kitchen_Countertops` varchar(50) DEFAULT NULL,
  `Landlord_Owner_Pays` text,
  `Landscape_Description` text,
  `Land_Use` varchar(100) DEFAULT NULL,
  `Last_Change_Timestamp` datetime DEFAULT NULL,
  `Last_Change_Type` varchar(57) DEFAULT NULL,
  `Last_List_Price` decimal(14,2) DEFAULT NULL,
  `Last_Status` varchar(57) DEFAULT NULL,
  `Lease_Description` text,
  `Lease_Option_Considered_Y` tinyint(1) DEFAULT NULL,
  `Lease_Price` decimal(14,2) DEFAULT NULL,
  `Leed_Certified` tinyint(1) DEFAULT NULL,
  `Legal_Description` varchar(225) DEFAULT NULL,
  `Length` int(11) DEFAULT NULL,
  `List_Agent_MUI` text,
  `List_Agent_Direct_Work_Phone` varchar(75) DEFAULT NULL,
  `List_Agent_Full_Name` varchar(175) DEFAULT NULL,
  `List_Agent_MLSID` varchar(50) DEFAULT NULL,
  `Listing_Agreement_Type` varchar(100) DEFAULT NULL,
  `Listing_Contract_Date` date DEFAULT NULL,
  `List_Office_MUI` text,
  `List_Office_MLSID` varchar(50) DEFAULT NULL,
  `List_Office_Name` varchar(75) DEFAULT NULL,
  `List_Office_Phone` varchar(75) DEFAULT NULL,
  `List_Price` decimal(14,2) DEFAULT NULL,
  `Litigation` varchar(100) DEFAULT NULL,
  `Litigation_Type` varchar(100) DEFAULT NULL,
  `Location` text,
  `Lot_Depth` int(11) DEFAULT NULL,
  `Lot_Description` text,
  `Lot_Front` varchar(100) DEFAULT NULL,
  `Lot_Frontage` int(11) DEFAULT NULL,
  `Lot_Number` varchar(30) DEFAULT NULL,
  `Lot_Sqft` int(11) DEFAULT NULL,
  `Maintenance` int(11) DEFAULT NULL,
  `Managed_By` varchar(100) DEFAULT NULL,
  `Management` int(11) DEFAULT NULL,
  `Manufactured` tinyint(1) DEFAULT NULL,
  `Map_Description` text,
  `Master_Bedroom_Down_YN` tinyint(1) DEFAULT NULL,
  `Master_Plan` varchar(100) DEFAULT NULL,
  `Master_Plan_Fee_Amount` int(11) DEFAULT NULL,
  `Master_Plan_Fee_MQYN` varchar(100) DEFAULT NULL,
  `Matrix_Unique_ID` text,
  `Matrix_Modified_DT` datetime DEFAULT NULL,
  `Media_Room_YN` tinyint(1) DEFAULT NULL,
  `Metro_Map_Coor_XP` varchar(27) DEFAULT NULL,
  `Metro_Map_Page_XP` int(11) DEFAULT NULL,
  `MH_Yr_Blt` varchar(29) DEFAULT NULL,
  `Miscellaneous_Description` text,
  `ML_Numof_Prop_Iffor_Sale` int(11) DEFAULT NULL,
  `MLS` varchar(57) DEFAULT NULL,
  `MLS_Number` varchar(45) DEFAULT NULL,
  `Model` varchar(35) DEFAULT NULL,
  `Net_Acres` decimal(14,2) DEFAULT NULL,
  `Next_Gen` text,
  `NOD_Date` datetime DEFAULT NULL,
  `NOI` int(11) DEFAULT NULL,
  `Num_Acres` decimal(14,2) DEFAULT NULL,
  `Numberof_Furnished_Units` int(11) DEFAULT NULL,
  `Numberof_Pets` int(11) DEFAULT NULL,
  `Numberof_Pets` int(11) DEFAULT NULL,
  `Num_Bldgs` int(11) DEFAULT NULL,
  `Num_Den_Other` int(11) DEFAULT NULL,
  `Num_Floors` int(11) DEFAULT NULL,
  `Num_G_Acres` decimal(14,2) DEFAULT NULL,
  `Num_Loft` int(11) DEFAULT NULL,
  `Numof_Loft_Areas` int(11) DEFAULT NULL,
  `Numof_Parking_Spaces_Included` int(11) DEFAULT NULL,
  `Num_Parcels` int(11) DEFAULT NULL,
  `Num_Parking` int(11) DEFAULT NULL,
  `Num_Storage_Units` int(11) DEFAULT NULL,
  `Num_Terraces` int(11) DEFAULT NULL,
  `Num_Units` varchar(100) DEFAULT NULL,
  `Off_Market_Date` date DEFAULT NULL,
  `On_Site_Staff` tinyint(1) DEFAULT NULL,
  `On_Site_Staff_Includes` text,
  `Original_Entry_Timestamp` datetime DEFAULT NULL,
  `Original_List_Price` decimal(14,2) DEFAULT NULL,
  `Other_Appliance_Description` text,
  `Other_Deposit` int(11) DEFAULT NULL,
  `Other_Encumbrance_Desc` text,
  `Other_Income_Description` text,
  `Other_Refund` varchar(100) DEFAULT NULL,
  `Oven_Description` text,
  `Oven_Fuel` varchar(100) DEFAULT NULL,
  `Owner_Licensee` varchar(100) DEFAULT NULL,
  `Owner_Managed` tinyint(1) DEFAULT NULL,
  `Ownership` varchar(100) DEFAULT NULL,
  `Owners_Name` varchar(45) DEFAULT NULL,
  `Owner_Will_Carry` tinyint(1) DEFAULT NULL,
  `Package_Available` tinyint(1) DEFAULT NULL,
  `Parcel_Number` varchar(75) DEFAULT NULL,
  `Parking_Description` text,
  `Parking_Level` varchar(28) DEFAULT NULL,
  `Parking_Space_ID_Num` varchar(40) DEFAULT NULL,
  `Paved_Road` varchar(100) DEFAULT NULL,
  `Pending_Date` date DEFAULT NULL,
  `Permitted_Property_Manager` tinyint(1) DEFAULT NULL,
  `Per_Pet_YN` tinyint(1) DEFAULT NULL,
  `Pet_Deposit` int(11) DEFAULT NULL,
  `Pet_Description` text,
  `Pet_Refund` varchar(100) DEFAULT NULL,
  `Pets_Allowed` tinyint(1) DEFAULT NULL,
  `Photo_Count` int(11) DEFAULT NULL,
  `Photo_Excluded` tinyint(1) DEFAULT NULL,
  `Photo_Instructions` varchar(100) DEFAULT NULL,
  `Photo_Modification_Timestamp` datetime DEFAULT NULL,
  `Pool_Description` text,
  `Pool_Length` int(11) DEFAULT NULL,
  `Pool_Width` int(11) DEFAULT NULL,
  `Postal_Code` varchar(35) DEFAULT NULL,
  `Postal_Code_Plus_4` varchar(29) DEFAULT NULL,
  `Poweronor_Off` varchar(100) DEFAULT NULL,
  `Previous_Parcel_Number` varchar(36) DEFAULT NULL,
  `Price_Change_Timestamp` datetime DEFAULT NULL,
  `Price_Chg_Date` datetime DEFAULT NULL,
  `Price_Per_Acre` int(11) DEFAULT NULL,
  `Primary_View_Direction` varchar(100) DEFAULT NULL,
  `Proj_Amenities_Description` text,
  `Prop_Amenities_Description` text,
  `Property_Condition` varchar(100) DEFAULT NULL,
  `Property_Description` text,
  `Property_Insurance` int(11) DEFAULT NULL,
  `Property_Sub_Type` varchar(57) DEFAULT NULL,
  `Property_Type` varchar(57) DEFAULT NULL,
  `Provider_Key` varchar(50) DEFAULT NULL,
  `Provider_Modification_Timestamp` datetime DEFAULT NULL,
  `Public_Address` varchar(125) DEFAULT NULL,
  `Public_Address_YN` tinyint(1) DEFAULT NULL,
  `Public_Remarks` text,
  `Pv_Pool` tinyint(1) DEFAULT NULL,
  `Range` int(11) DEFAULT NULL,
  `RATIO_Close_Price_By_List_Price` decimal(14,2) DEFAULT NULL,
  `RATIO_Close_Price_By_Original_Li` decimal(14,2) DEFAULT NULL,
  `RATIO_Current_Price_By_SQFT` decimal(14,2) DEFAULT NULL,
  `Realtor_YN` tinyint(1) DEFAULT NULL,
  `Refrigerator_Description` text,
  `Refrigerator_YN` tinyint(1) DEFAULT NULL,
  `Rented_Price` int(11) DEFAULT NULL,
  `Rent_Range` varchar(45) DEFAULT NULL,
  `Rent_Terms_Description` text,
  `Repo_Reo_YN` tinyint(1) DEFAULT NULL,
  `Road` text,
  `Roof_Description` text,
  `Room_Count` int(11) DEFAULT NULL,
  `Sale_Office_Bonus_YN` tinyint(1) DEFAULT NULL,
  `Sale_Type` varchar(100) DEFAULT NULL,
  `Second_Encumbrance_Assumable` varchar(100) DEFAULT NULL,
  `Second_Encumbrance_Balance` int(11) DEFAULT NULL,
  `Second_Encumbrance_Payment` int(11) DEFAULT NULL,
  `Second_Encumbrance_Pmt_Desc` text,
  `Second_Encumbrance_Rate` decimal(14,2) DEFAULT NULL,
  `Section` int(11) DEFAULT NULL,
  `Section_8_Considered_YN` tinyint(1) DEFAULT NULL,
  `Security` text,
  `Security_Deposit` int(11) DEFAULT NULL,
  `Security_Refund` varchar(100) DEFAULT NULL,
  `Seller_Contribution` decimal(14,2) DEFAULT NULL,
  `Selling_Agent_MUI` text,
  `Selling_Agent_Direct_Work_Phone` varchar(75) DEFAULT NULL,
  `Selling_Agent_Full_Name` varchar(175) DEFAULT NULL,
  `Selling_Agent_MLSID` varchar(50) DEFAULT NULL,
  `Selling_Office_MUI` text,
  `Selling_Office_MLSID` varchar(50) DEFAULT NULL,
  `Selling_Office_Name` varchar(75) DEFAULT NULL,
  `Selling_Office_Phone` varchar(75) DEFAULT NULL,
  `Separate_Meter` text,
  `Service_Contract_Inc` text,
  `Services_Available_On_Site` text,
  `Sewer` text,
  `Short_Sale` tinyint(1) DEFAULT NULL,
  `Showing_Agent_Public_ID` varchar(40) DEFAULT NULL,
  `SIDLID_Annual_Amount` int(11) DEFAULT NULL,
  `SIDLID_Balance` int(11) DEFAULT NULL,
  `SIDLIDYN` tinyint(1) DEFAULT NULL,
  `Solar_Electric` varchar(100) DEFAULT NULL,
  `Sold_Appraisal_NUMBER` int(11) DEFAULT NULL,
  `Sold_Balloon_Amt` int(11) DEFAULT NULL,
  `Sold_Balloon_Due` varchar(30) DEFAULT NULL,
  `Sold_Down_Payment` int(11) DEFAULT NULL,
  `Sold_Lease_Description` text,
  `Sold_OWC_Amt` int(11) DEFAULT NULL,
  `Sold_Term` varchar(100) DEFAULT NULL,
  `Spa` varchar(100) DEFAULT NULL,
  `Spa_Description` text,
  `Sq_Ft_Total` int(11) DEFAULT NULL,
  `State_Or_Province` varchar(27) DEFAULT NULL,
  `Status` varchar(57) DEFAULT NULL,
  `Status_Change_Timestamp` datetime DEFAULT NULL,
  `Status_Contractual_Search_Date` date DEFAULT NULL,
  `Status_Update` varchar(100) DEFAULT NULL,
  `Storage_Secure` tinyint(1) DEFAULT NULL,
  `Storage_Unit_Desc` varchar(100) DEFAULT NULL,
  `Storage_Unit_Dim` varchar(30) DEFAULT NULL,
  `Street_Dir_Prefix` varchar(57) DEFAULT NULL,
  `Street_Dir_Suffix` varchar(57) DEFAULT NULL,
  `Street_Name` varchar(75) DEFAULT NULL,
  `Street_Number` varchar(50) DEFAULT NULL,
  `Street_Number_Numeric` int(11) DEFAULT NULL,
  `Street_Suffix` varchar(57) DEFAULT NULL,
  `Studio_YN` tinyint(1) DEFAULT NULL,
  `Style` text,
  `Subdivision_Name` varchar(85) DEFAULT NULL,
  `Subdivision_Number` int(11) DEFAULT NULL,
  `Subdivision_Num_Search` varchar(30) DEFAULT NULL,
  `Subjectto_FIRPTAYN` tinyint(1) DEFAULT NULL,
  `Table` varchar(100) DEFAULT NULL,
  `Tax_District` varchar(55) DEFAULT NULL,
  `Temp_Off_Market_Date` date DEFAULT NULL,
  `Temp_Off_Mrkt_Status_Desc` varchar(100) DEFAULT NULL,
  `Tenant_Pays` text,
  `Terms_Owner_Will_Carry` int(11) DEFAULT NULL,
  `Terrace_Location` text,
  `Terrace_Total_Sqft` int(11) DEFAULT NULL,
  `Terrain_Description` text,
  `Three_Qtr_Baths` int(11) DEFAULT NULL,
  `Total_Floors` varchar(28) DEFAULT NULL,
  `Total_Numof_Parking_Spaces` decimal(14,2) DEFAULT NULL,
  `Tower_Name` varchar(100) DEFAULT NULL,
  `Town` varchar(100) DEFAULT NULL,
  `Township` int(11) DEFAULT NULL,
  `Transaction_Type` varchar(57) DEFAULT NULL,
  `Trash` int(11) DEFAULT NULL,
  `T_Status_Date` datetime DEFAULT NULL,
  `Type` varchar(100) DEFAULT NULL,
  `Type_Owner_Will_Carry` text,
  `Unit_Count` int(11) DEFAULT NULL,
  `Unit_Description` text,
  `Unit_Number` varchar(50) DEFAULT NULL,
  `Unit_Pool_Indoor_YN` tinyint(1) DEFAULT NULL,
  `Unit_Spa_Indoor` tinyint(1) DEFAULT NULL,
  `Utilities` int(11) DEFAULT NULL,
  `Utilities_Incl` text,
  `Utility_Information` text,
  `Views` text,
  `Virtual_Tour_Link` varchar(280) DEFAULT NULL,
  `Washer` varchar(100) DEFAULT NULL,
  `Washer_Dryer_Description` varchar(100) DEFAULT NULL,
  `Washer_Dryer_Included` varchar(100) DEFAULT NULL,
  `Washer_Dryer_Location` text,
  `Washer_Included` tinyint(1) DEFAULT NULL,
  `Water` text,
  `Water_Heater_Description` text,
  `Weight_Limit` int(11) DEFAULT NULL,
  `Width` int(11) DEFAULT NULL,
  `Year_Built` int(11) DEFAULT NULL,
  `Yearly_Operating_Expense` int(11) DEFAULT NULL,
  `Yearly_Operating_Income` int(11) DEFAULT NULL,
  `Yearly_Other_Income` int(11) DEFAULT NULL,
  `Year_Round_School_YN` tinyint(1) DEFAULT NULL,
  `Yrs_Remaining` int(11) DEFAULT NULL,
  `Zoning` text,
  `Zoning_Authority` varchar(100) DEFAULT NULL,
  KEY `Property_Type` (`Property_Type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;